// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/motionrobot/webdoc/proto/serp.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenericSearchResponse_SearchType int32

const (
	GenericSearchResponse_SEARCH_TYPE_UNKNOWN GenericSearchResponse_SearchType = 0
	GenericSearchResponse_GOOGLE              GenericSearchResponse_SearchType = 1
	GenericSearchResponse_BING                GenericSearchResponse_SearchType = 2
)

var GenericSearchResponse_SearchType_name = map[int32]string{
	0: "SEARCH_TYPE_UNKNOWN",
	1: "GOOGLE",
	2: "BING",
}

var GenericSearchResponse_SearchType_value = map[string]int32{
	"SEARCH_TYPE_UNKNOWN": 0,
	"GOOGLE":              1,
	"BING":                2,
}

func (x GenericSearchResponse_SearchType) String() string {
	return proto.EnumName(GenericSearchResponse_SearchType_name, int32(x))
}

func (GenericSearchResponse_SearchType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc1c83960f67ef9, []int{1, 0}
}

type GenericSearchResponse_SearchVertical int32

const (
	GenericSearchResponse_VERTICAL_UNKNOWN GenericSearchResponse_SearchVertical = 0
	GenericSearchResponse_WEB              GenericSearchResponse_SearchVertical = 1
	GenericSearchResponse_IMAGE            GenericSearchResponse_SearchVertical = 2
)

var GenericSearchResponse_SearchVertical_name = map[int32]string{
	0: "VERTICAL_UNKNOWN",
	1: "WEB",
	2: "IMAGE",
}

var GenericSearchResponse_SearchVertical_value = map[string]int32{
	"VERTICAL_UNKNOWN": 0,
	"WEB":              1,
	"IMAGE":            2,
}

func (x GenericSearchResponse_SearchVertical) String() string {
	return proto.EnumName(GenericSearchResponse_SearchVertical_name, int32(x))
}

func (GenericSearchResponse_SearchVertical) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc1c83960f67ef9, []int{1, 1}
}

type Result struct {
	Pos                  uint32   `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Snippet              string   `protobuf:"bytes,5,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Site                 string   `protobuf:"bytes,6,opt,name=site,proto3" json:"site,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc1c83960f67ef9, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetPos() uint32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Result) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Result) GetSnippet() string {
	if m != nil {
		return m.Snippet
	}
	return ""
}

func (m *Result) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *Result) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

type GenericSearchResponse struct {
	Query                string    `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ParsedQuery          string    `protobuf:"bytes,2,opt,name=ParsedQuery,proto3" json:"ParsedQuery,omitempty"`
	Url                  string    `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	StartPos             uint32    `protobuf:"varint,4,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	Results              []*Result `protobuf:"bytes,10,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GenericSearchResponse) Reset()         { *m = GenericSearchResponse{} }
func (m *GenericSearchResponse) String() string { return proto.CompactTextString(m) }
func (*GenericSearchResponse) ProtoMessage()    {}
func (*GenericSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc1c83960f67ef9, []int{1}
}

func (m *GenericSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericSearchResponse.Unmarshal(m, b)
}
func (m *GenericSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericSearchResponse.Marshal(b, m, deterministic)
}
func (m *GenericSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericSearchResponse.Merge(m, src)
}
func (m *GenericSearchResponse) XXX_Size() int {
	return xxx_messageInfo_GenericSearchResponse.Size(m)
}
func (m *GenericSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericSearchResponse proto.InternalMessageInfo

func (m *GenericSearchResponse) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *GenericSearchResponse) GetParsedQuery() string {
	if m != nil {
		return m.ParsedQuery
	}
	return ""
}

func (m *GenericSearchResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GenericSearchResponse) GetStartPos() uint32 {
	if m != nil {
		return m.StartPos
	}
	return 0
}

func (m *GenericSearchResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type SERPScrapeInfo struct {
	ResultPage           *GenericSearchResponse `protobuf:"bytes,1,opt,name=result_page,json=resultPage,proto3" json:"result_page,omitempty"`
	CachedFiles          map[uint32]string      `protobuf:"bytes,2,rep,name=cached_files,json=cachedFiles,proto3" json:"cached_files,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SERPScrapeInfo) Reset()         { *m = SERPScrapeInfo{} }
func (m *SERPScrapeInfo) String() string { return proto.CompactTextString(m) }
func (*SERPScrapeInfo) ProtoMessage()    {}
func (*SERPScrapeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc1c83960f67ef9, []int{2}
}

func (m *SERPScrapeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SERPScrapeInfo.Unmarshal(m, b)
}
func (m *SERPScrapeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SERPScrapeInfo.Marshal(b, m, deterministic)
}
func (m *SERPScrapeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SERPScrapeInfo.Merge(m, src)
}
func (m *SERPScrapeInfo) XXX_Size() int {
	return xxx_messageInfo_SERPScrapeInfo.Size(m)
}
func (m *SERPScrapeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SERPScrapeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SERPScrapeInfo proto.InternalMessageInfo

func (m *SERPScrapeInfo) GetResultPage() *GenericSearchResponse {
	if m != nil {
		return m.ResultPage
	}
	return nil
}

func (m *SERPScrapeInfo) GetCachedFiles() map[uint32]string {
	if m != nil {
		return m.CachedFiles
	}
	return nil
}

func init() {
	proto.RegisterEnum("serpproto.GenericSearchResponse_SearchType", GenericSearchResponse_SearchType_name, GenericSearchResponse_SearchType_value)
	proto.RegisterEnum("serpproto.GenericSearchResponse_SearchVertical", GenericSearchResponse_SearchVertical_name, GenericSearchResponse_SearchVertical_value)
	proto.RegisterType((*Result)(nil), "serpproto.Result")
	proto.RegisterType((*GenericSearchResponse)(nil), "serpproto.GenericSearchResponse")
	proto.RegisterType((*SERPScrapeInfo)(nil), "serpproto.SERPScrapeInfo")
	proto.RegisterMapType((map[uint32]string)(nil), "serpproto.SERPScrapeInfo.CachedFilesEntry")
}

func init() {
	proto.RegisterFile("github.com/motionrobot/webdoc/proto/serp.proto", fileDescriptor_2cc1c83960f67ef9)
}

var fileDescriptor_2cc1c83960f67ef9 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0x6e, 0xd3, 0x4a,
	0x10, 0xc6, 0x8f, 0x9d, 0xff, 0x93, 0xb6, 0xf2, 0x59, 0x40, 0x58, 0x70, 0x13, 0xa5, 0x42, 0x8a,
	0x40, 0x72, 0xa4, 0x72, 0x83, 0x8a, 0x84, 0x94, 0x44, 0x26, 0x44, 0xb4, 0x49, 0xd8, 0x24, 0xad,
	0xe0, 0xc6, 0xda, 0x38, 0xd3, 0x64, 0x55, 0xc7, 0x6b, 0x76, 0xd7, 0xa0, 0xbc, 0x0f, 0x4f, 0xc0,
	0x23, 0xf1, 0x24, 0x68, 0xd7, 0xa4, 0xa4, 0x88, 0x0b, 0xae, 0xfc, 0xcd, 0x6f, 0x67, 0xbc, 0x33,
	0xdf, 0x2c, 0x04, 0x6b, 0xae, 0x37, 0xf9, 0x32, 0x88, 0xc5, 0xb6, 0xbb, 0x15, 0x9a, 0x8b, 0x54,
	0x8a, 0xa5, 0xd0, 0xdd, 0xaf, 0xb8, 0x5c, 0x89, 0xb8, 0x9b, 0x49, 0xa1, 0x45, 0x57, 0xa1, 0xcc,
	0x02, 0x2b, 0x49, 0xc3, 0x68, 0x2b, 0xdb, 0xdf, 0x1d, 0xa8, 0x52, 0x54, 0x79, 0xa2, 0x89, 0x07,
	0xa5, 0x4c, 0x28, 0xdf, 0x69, 0x39, 0x9d, 0x63, 0x6a, 0xa4, 0x21, 0xb9, 0x4c, 0x7c, 0xb7, 0xe5,
	0x74, 0x1a, 0xd4, 0x48, 0xf2, 0x14, 0x1a, 0x7c, 0xcb, 0xd6, 0x18, 0x19, 0x5e, 0xb2, 0xbc, 0x6e,
	0xc1, 0x42, 0x26, 0xe4, 0x21, 0x54, 0x34, 0xd7, 0x09, 0xfa, 0x65, 0x7b, 0x50, 0x04, 0xc4, 0x87,
	0x9a, 0x4a, 0x79, 0x96, 0xa1, 0xf6, 0x2b, 0x96, 0xef, 0x43, 0x42, 0xa0, 0xac, 0xb8, 0x46, 0xbf,
	0x6a, 0xb1, 0xd5, 0xe4, 0x14, 0x8e, 0xf5, 0x26, 0xdf, 0x2e, 0x53, 0xc6, 0x13, 0x7b, 0x49, 0xcd,
	0x1e, 0x1e, 0xdd, 0xc1, 0x85, 0x4c, 0xda, 0xdf, 0x5c, 0x78, 0x34, 0xc4, 0x14, 0x25, 0x8f, 0x67,
	0xc8, 0x64, 0xbc, 0xa1, 0xa8, 0x32, 0x91, 0x2a, 0x34, 0x2d, 0x7c, 0xce, 0x51, 0xee, 0xec, 0x14,
	0x0d, 0x5a, 0x04, 0xa4, 0x05, 0xcd, 0x29, 0x93, 0x0a, 0x57, 0x1f, 0xec, 0x59, 0x31, 0xcf, 0x21,
	0xda, 0x4f, 0x5a, 0xba, 0x37, 0xa9, 0xd2, 0x4c, 0xea, 0xc8, 0x78, 0x52, 0xb6, 0x9e, 0xd4, 0x2d,
	0x98, 0x0a, 0x45, 0x5e, 0x40, 0x4d, 0x5a, 0xd3, 0x94, 0x0f, 0xad, 0x52, 0xa7, 0x79, 0xf6, 0x7f,
	0x70, 0x67, 0x69, 0x50, 0xd8, 0x49, 0xf7, 0x19, 0xed, 0xd7, 0x00, 0x45, 0x97, 0xf3, 0x5d, 0x86,
	0xe4, 0x31, 0x3c, 0x98, 0x85, 0x3d, 0x3a, 0x78, 0x17, 0xcd, 0x3f, 0x4e, 0xc3, 0x68, 0x31, 0x7e,
	0x3f, 0x9e, 0x5c, 0x8f, 0xbd, 0xff, 0x08, 0x40, 0x75, 0x38, 0x99, 0x0c, 0x2f, 0x42, 0xcf, 0x21,
	0x75, 0x28, 0xf7, 0x47, 0xe3, 0xa1, 0xe7, 0xb6, 0xcf, 0xe1, 0xa4, 0x28, 0xbe, 0x42, 0xa9, 0x79,
	0xcc, 0x8c, 0xcb, 0xde, 0x55, 0x48, 0xe7, 0xa3, 0x41, 0xef, 0xe2, 0xa0, 0xba, 0x06, 0xa5, 0xeb,
	0xb0, 0xef, 0x39, 0xa4, 0x01, 0x95, 0xd1, 0x65, 0x6f, 0x18, 0x7a, 0x6e, 0xfb, 0x87, 0x03, 0x27,
	0xb3, 0x90, 0x4e, 0x67, 0xb1, 0x64, 0x19, 0x8e, 0xd2, 0x1b, 0x41, 0x7a, 0xd0, 0x2c, 0xda, 0x8a,
	0x32, 0xb6, 0x46, 0xeb, 0x52, 0xf3, 0xac, 0x75, 0xd0, 0xfc, 0x5f, 0x6d, 0xa5, 0x50, 0x14, 0x4d,
	0xd9, 0x1a, 0xc9, 0x25, 0x1c, 0xc5, 0x2c, 0xde, 0xe0, 0x2a, 0xba, 0xe1, 0x09, 0x2a, 0xdf, 0xb5,
	0x06, 0x3c, 0x3f, 0xf8, 0xc7, 0xfd, 0x3b, 0x83, 0x81, 0xcd, 0x7e, 0x6b, 0x92, 0xc3, 0x54, 0xcb,
	0x1d, 0x6d, 0xc6, 0xbf, 0xc9, 0x93, 0x37, 0xe0, 0xfd, 0x99, 0x60, 0xb6, 0x71, 0x8b, 0xbb, 0xfd,
	0x4b, 0xbc, 0xc5, 0x9d, 0xd9, 0xeb, 0x17, 0x96, 0xe4, 0xf8, 0x6b, 0x77, 0x45, 0x70, 0xee, 0xbe,
	0x72, 0xfa, 0xcf, 0x3e, 0x9d, 0xfe, 0xc3, 0xeb, 0x5f, 0x56, 0xed, 0xe7, 0xe5, 0xcf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xe3, 0x09, 0xc4, 0x89, 0x2b, 0x03, 0x00, 0x00,
}
